/** All server data is rendered with textContent; no task content is interpreted as HTML. */
export const TASK_PAGE_HTML = String.raw`<!doctype html>
<html lang="zh"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Task · 执行记录</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f5f6f8;color:#202936;font:14px system-ui}header{height:64px;display:flex;align-items:center;gap:22px;padding:0 24px;border-bottom:1px solid #ddd;background:white}a{color:#355b9b}h1{font-size:21px}h2{font-size:17px}h3{font-size:14px}.layout{display:grid;grid-template-columns:270px minmax(360px,1fr) minmax(320px,40%);height:calc(100vh - 64px)}aside,main,section.detail{overflow:auto;padding:20px;border-right:1px solid #dde1e6}button,input,select{font:inherit;border:1px solid #d3dae4;border-radius:7px;padding:9px;background:white;color:inherit}button{cursor:pointer;text-align:left}button:hover,button.active{border-color:#436ec0;background:#eef3ff}input,select{width:100%;margin-bottom:10px}.muted{color:#67758a;font-size:12px;overflow-wrap:anywhere}.task{display:block;width:100%;margin:8px 0}.task strong{display:block;overflow-wrap:anywhere}.card{background:white;border:1px solid #dce2ea;border-radius:10px;padding:16px;margin-bottom:14px;overflow-wrap:anywhere}.badge{display:inline-block;padding:3px 7px;border-radius:5px;background:#edf1f6;margin-right:8px;font-size:12px}.node{margin:10px 0;border-left:3px solid #aab7ce;padding-left:10px}.node.review{border-color:#9064c8}.node.delivery{border-color:#27856e}.node summary{cursor:pointer}.node button{display:block;margin-top:8px;width:100%}.error{color:#ac352c}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.6 ui-monospace,monospace;background:#f1f3f6;padding:12px;border-radius:7px}.tabs{display:flex;gap:6px;margin:14px 0}.tree{margin-left:14px;border-left:1px solid #ddd;padding-left:8px}.metrics{display:flex;gap:12px;flex-wrap:wrap;margin-top:12px}@media(max-width:1000px){.layout{grid-template-columns:220px 1fr}.detail{grid-column:1/-1;min-height:400px}.layout{height:auto}aside,main{max-height:75vh}}
.json-view{border:1px solid #dce2ea;border-radius:8px;margin:10px 0;background:#f1f3f6}.json-tools{display:flex;gap:6px;align-items:center;flex-wrap:wrap;padding:8px}.json-tools button{padding:4px 8px}.json-tree{font:var(--json-size,12px)/1.6 ui-monospace,monospace;padding:10px;max-height:480px;min-height:100px;overflow:auto;resize:vertical}.json-tree details{margin-left:14px}.json-tree summary{cursor:pointer;white-space:pre-wrap;overflow-wrap:anywhere}.json-leaf{white-space:pre-wrap;overflow-wrap:anywhere;margin-left:14px}.json-dialog{width:94vw;max-width:none;height:92vh;border:1px solid #ccd5e1;border-radius:10px;padding:16px}.json-dialog::backdrop{background:#15203488}.json-dialog .json-tree{max-height:none;height:calc(92vh - 150px);resize:none}.json-dialog .json-view{margin:0}.milestone{padding:8px 12px;margin:6px 0;border-left:2px solid #bbc5d2}
</style></head><body><!-- initial -->
<header><h1>任务执行记录</h1><a href="/admin/traces">历史 Trace / 记忆</a><a href="/admin/models">模型与账户</a><button id="refresh">刷新</button><span id="notice" class="muted"></span></header>
<div class="layout"><aside><input id="search" aria-label="搜索任务" placeholder="目标、Task ID、Conversation"><select id="status" aria-label="筛选状态"><option value="">全部状态</option></select><div id="list"></div></aside><main id="timeline">选择一个任务查看执行过程。</main><section class="detail" id="detail">选择输入、Run、Review 或投递节点查看详情。</section></div>
<script>
const $=id=>document.getElementById(id),el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=String(text);if(cls)e.className=cls;return e};
const labels={input:'用户输入',run:'Agent Run',request:'排队 / 应用处理',review:'独立 Review',delivery:'回复投递',run_started:'开始执行',review_started:'申请完成核对',review_result:'Review 结论',settled:'状态更新',control:'用户控制',stale_result:'过期结果，未推进任务',turn_failed:'执行失败'};
const stateNames={QUEUED:'排队中',RUNNING:'执行中',REVIEWING:'核对中',WAITING:'等待用户',PAUSING:'正在暂停',PAUSED:'已暂停',CANCELLING:'正在取消',COMPLETED:'已完成',FAILED:'失败',CANCELLED:'已取消',SUCCEEDED:'执行结束',succeeded:'成功',failed:'失败',running:'运行中',incomplete:'记录不完整',SENT:'已送达',PENDING:'待发送',SENDING:'发送中',RETRY_WAIT:'等待重试'};
let tasks=[],selected=new URLSearchParams(location.search).get('task')||'',generation=0;
async function get(url){const r=await fetch(url);if(!r.ok)throw Error('读取失败（'+r.status+'）');return r.json()}
function json(value){
 const wrap=el('div',null,'json-view'),tools=el('div',null,'json-tools'),tree=el('div',null,'json-tree');let size=12;tree.tabIndex=0;tree.setAttribute('aria-label','JSON 内容');
 function branch(key,v,depth){if(v!==null&&typeof v==='object'){const d=el('details'),entries=Object.entries(v);d.open=depth<1;d.append(el('summary',key+(Array.isArray(v)?'Array':'Object')+' · '+entries.length+' 项'));let loaded=false;const populate=()=>{if(loaded)return;loaded=true;for(const [k,item]of entries)d.append(branch(k+': ',item,depth+1));};d.addEventListener('toggle',()=>{if(d.open)populate()});d.populate=populate;if(d.open)populate();return d;}return el('div',key+JSON.stringify(v??null),'json-leaf');}
 tree.append(branch('',value,0));
 function button(label,action){const b=el('button',label);b.onclick=action;tools.append(b);return b;}
 const zoom=el('span','12px','muted');function scale(delta){size=Math.max(10,Math.min(24,size+delta));wrap.style.setProperty('--json-size',size+'px');zoom.textContent=size+'px';}
 button('A−',()=>scale(-1));button('A+',()=>scale(1));tools.append(zoom);
 button('全部折叠',()=>tree.querySelectorAll('details').forEach(d=>d.open=false));
 button('全部展开',()=>{function expand(root){for(const d of Array.from(root.children)){if(d.tagName==='DETAILS'){d.populate?.();d.open=true;expand(d);}}}expand(tree);});
 button('放大阅读',()=>{if(wrap.closest('dialog'))return;const dialog=el('dialog',null,'json-dialog'),close=el('button','关闭（Esc）'),anchor=document.createComment('json-position');wrap.before(anchor);dialog.append(close,wrap);document.body.append(dialog);close.onclick=()=>dialog.close();dialog.addEventListener('close',()=>{anchor.replaceWith(wrap);dialog.remove()},{once:true});dialog.showModal();close.focus();});
 wrap.append(tools,tree);return wrap;
}function time(at){return at?new Date(at).toLocaleString('zh-CN',{hour12:false}):'时间未记录'}
function list(){const q=$('search').value.toLowerCase(),status=$('status').value;const groups=new Map();for(const t of tasks){if(status&&t.status!==status)continue;if(q&&!(t.goal+' '+t.id+' '+t.conversationId).toLowerCase().includes(q))continue;if(!groups.has(t.conversationId))groups.set(t.conversationId,[]);groups.get(t.conversationId).push(t)}$('list').replaceChildren();for(const [id,items]of groups){$('list').append(el('h3','Conversation'),el('div',id,'muted'));for(const t of items){const b=el('button',null,'task'+(selected===t.id?' active':''));b.append(el('strong',t.goal||'附件任务'),el('span',stateNames[t.status]||t.status,'badge'),el('div',time(t.updatedAt),'muted'));b.onclick=()=>{selected=t.id;history.replaceState(null,'','?task='+encodeURIComponent(selected));list();void load()};$('list').append(b)}}if(!groups.size)$('list').append(el('p','没有匹配的任务。','muted'))}
function metric(u){return (u.complete?'':'已知 ') + u.tokens+' Tokens'+(u.complete?'':' · 数据不完整')+' / '+(u.durationMs/1000).toFixed(2)+'s'+(u.durationComplete?'':'（耗时不完整）')}
async function load(){const version=++generation;if(!selected)return;try{const p=await get('/debug/tasks/'+encodeURIComponent(selected)+'/trace');if(version!==generation)return;const t=p.task;$('timeline').replaceChildren();const top=el('div',null,'card');top.append(el('h2',t.goal||'附件任务'),el('span',stateNames[t.status]||t.status,'badge'),el('span','版本 '+t.revision,'badge'),el('div',t.id,'muted'),el('p',t.progress||'尚无进展'),el('p',t.waitQuestion||t.stopReason||''));const counts=el('div',null,'metrics');counts.append(el('strong','执行预算 '+t.reactUsed+' / '+t.reactLimit),el('strong','Review '+t.reviewCount+' 次'));top.append(counts,el('p','执行：'+metric(p.usage.execution),'muted'),el('p','Review：'+metric(p.usage.review),'muted'),el('p','总 Token：'+p.usage.totalTokens+(p.usage.complete?'':'（数据不完整）'),'muted'));const latest=p.inputs.at(-1);if(latest)top.append(el('h3','最新用户输入'),el('p',latest.text||'附件输入'));top.append(el('div','任务完成与消息送达分别记录；下方投递节点反映实际发送状态。','muted'));$('timeline').append(top);
const newestRun=[...p.nodes].reverse().find(n=>n.kind==='run');for(const n of p.nodes){if(['run_started','review_started','control','stale_result','settled','turn_failed'].includes(n.kind)){const row=el('div',null,'milestone'),data=n.data||{};row.append(el('strong',labels[n.kind]||n.title),el('div',time(n.at)+' · '+(data.reason||data.action||data.status||'历史关联信息不完整'),'muted'));const b=el('button','详情');b.onclick=()=>inspect(n);row.append(b);$('timeline').append(row);continue;}const box=el('details',null,'node '+n.kind);box.open=n.kind!=='run'||n.id===newestRun?.id||['FAILED','RUNNING','PAUSED'].includes(n.status);const head=el('summary',(labels[n.kind]||n.title)+' · '+time(n.at));head.append(el('span',' '+(stateNames[n.status]||n.status||''),'badge'));if(n.revision)head.append(el('span',' v'+n.revision,'muted'));box.append(head);if(n.superseded)box.append(el('p','历史版本；以状态事件确认结果是否被接纳。','muted'));const b=el('button',n.kind==='input'?n.title:'查看详情');b.onclick=()=>inspect(n);box.append(b);if(n.kind==='run')box.append(el('div',n.data.publication,'muted'));const spans=n.spans||[];function tree(parent,target){for(const span of spans.filter(s=>(s.parentId||null)===parent)){const wrap=el('div',null,'tree'),button=el('button',span.name+' · '+span.status);button.onclick=()=>inspect({kind:'span',title:span.name,data:span});wrap.append(button);target.append(wrap);tree(span.id,wrap)}}tree(null,box);$('timeline').append(box)}
if(p.nodes.length)inspect(p.nodes.at(-1));$('notice').textContent='已更新 '+time(new Date());}catch(e){if(version===generation){$('timeline').replaceChildren(el('p',e.message,'error'));$('detail').replaceChildren();}}}
function inspect(n){const root=$('detail');root.replaceChildren(el('h2',labels[n.kind]||n.title||n.kind));const tabs=el('div',null,'tabs'),body=el('div');const data=n.data||{};if(n.lifecycle?.length){root.append(el('h3','执行阶段记录'));for(const event of n.lifecycle){root.append(el('p',(labels[event.type]||event.type)+' · '+time(event.at)));if(event.data?.decision)root.append(el('p',event.data.decision+' · '+(event.data.reason||'')));}root.append(json(n.lifecycle));}const render=mode=>{body.replaceChildren();if(mode==='raw'){body.append(json(n));return}if(mode==='request'){body.append(json(data.input||data.context||data));return}if(n.kind==='run'||n.kind==='request'){body.append(el('h3','执行上下文 / 目标版本'),json(data.context),el('h3','结构化结果'),json(data.outcome),el('h3','应用结果'),el('p',data.result||'尚无结果'),el('p',data.publication));if(!data.traceAvailable)body.append(el('p','调用详情未记录或已超出保留范围。','muted'));}else if(n.kind==='review'||n.kind==='span'){body.append(el('h3','输入'),json(data.input),el('h3','输出'),json(data.output),el('h3','用量'),json(data.usage));}else {const fields={text:'用户输入',replyTo:'回应的问题',decision:'核对结论',reason:'原因',gaps:'待解决缺口',nextAction:'下一步',question:'需要用户补充',finalResult:'最终结果',action:'用户操作',amount:'追加轮数',fromStatus:'原状态',toStatus:'新状态',status:'当前状态',revision:'目标版本',progress:'进展',evidence:'证据引用',reactLimitBefore:'原预算',reactLimitAfter:'新预算',attemptCount:'发送次数',lastError:'发送错误',textContent:'回复内容'};let shown=false;for(const [key,label]of Object.entries(fields)){if(data[key]!=null){shown=true;body.append(el('h3',label),typeof data[key]==='object'?json(data[key]):el('p',data[key]));}}if(!shown)body.append(json(data));}};for(const [mode,title]of [['summary','详情'],['request','请求 / 输入'],['raw','原始记录']]){const b=el('button',title);b.onclick=()=>render(mode);tabs.append(b)}root.append(tabs,body);render('summary');}
async function refresh(){try{tasks=await get('/debug/tasks');if(!selected&&tasks.length)selected=tasks[0].id;const previous=$('status').value;$('status').replaceChildren(el('option','全部状态'));$('status').firstChild.value='';for(const status of [...new Set(tasks.map(t=>t.status))]){const o=el('option',stateNames[status]||status);o.value=status;$('status').append(o)}$('status').value=previous;list();await load();}catch(e){$('notice').textContent=e.message}}
$('search').oninput=list;$('status').onchange=list;$('refresh').onclick=refresh;void refresh();
</script></body></html>`;
